analyzer:
  exclude:
    - build/**
  errors:
    unused_import: warning
    dead_code: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
